"""Prometheus observability helpers for opt-in runtime metrics.

This module is intentionally fail-open:
- If prometheus_client is unavailable, all helpers become no-ops.
- Metrics setup errors never block planner/apply/CLI execution paths.
"""

from __future__ import annotations

import os
import threading
from collections.abc import Mapping

from media_manager.app.core.logging_config import get_logger

logger = get_logger(__name__)

try:
    from prometheus_client import Counter, Gauge, Histogram, REGISTRY, generate_latest, make_asgi_app, start_http_server
except Exception:  # pragma: no cover - fallback path when dependency is unavailable.
    Counter = None  # type: ignore[assignment]
    Gauge = None  # type: ignore[assignment]
    Histogram = None  # type: ignore[assignment]
    REGISTRY = None  # type: ignore[assignment]
    generate_latest = None  # type: ignore[assignment]
    make_asgi_app = None  # type: ignore[assignment]
    start_http_server = None  # type: ignore[assignment]

_server_lock = threading.Lock()
_registry_lock = threading.Lock()
_canonical_cache_metrics_lock = threading.Lock()
_server_started = False
_canonical_cache_previous_totals: dict[tuple[str, str], tuple[int, int]] = {}


def _is_histogram_supported() -> bool:
    return Histogram is not None


def _is_server_supported() -> bool:
    return start_http_server is not None


def _get_registered_collector(name: str):
    if REGISTRY is None:
        return None
    names_to_collectors = getattr(REGISTRY, "_names_to_collectors", {})
    return names_to_collectors.get(name)


def _get_or_create_counter(name: str, documentation: str, labelnames: tuple[str, ...]):
    """Return a registered Counter, reusing an existing collector when present.

    This keeps module import robust under reload/hot-reload scenarios where the
    default registry already contains the same metric names.
    """
    if Counter is None:
        return None

    try:
        with _registry_lock:
            existing = _get_registered_collector(name)
            if existing is not None:
                return existing
            return Counter(name, documentation, labelnames)
    except Exception:
        logger.exception("Failed to initialize counter", extra={"phase": "observability", "action": "METRICS_INIT"})
        return None


def _get_or_create_histogram(
    name: str,
    documentation: str,
    labelnames: tuple[str, ...],
    *,
    buckets: tuple[float, ...] | None = None,
):
    if Histogram is None:
        return None

    try:
        with _registry_lock:
            existing = _get_registered_collector(name)
            if existing is not None:
                return existing
            if buckets is None:
                return Histogram(name, documentation, labelnames)
            return Histogram(name, documentation, labelnames, buckets=buckets)
    except Exception:
        logger.exception("Failed to initialize histogram", extra={"phase": "observability", "action": "METRICS_INIT"})
        return None


def _get_or_create_gauge(name: str, documentation: str, labelnames: tuple[str, ...]):
    if Gauge is None:
        return None

    try:
        with _registry_lock:
            existing = _get_registered_collector(name)
            if existing is not None:
                return existing
            return Gauge(name, documentation, labelnames)
    except Exception:
        logger.exception("Failed to initialize gauge", extra={"phase": "observability", "action": "METRICS_INIT"})
        return None


if Counter is not None:
    _INGEST_FILES_SCANNED_TOTAL = _get_or_create_counter(
        "ingest_files_scanned_total",
        "Total files scanned across ingest runs.",
        ("run_id", "phase"),
    )
    _INGEST_NEW_CONTENTS_TOTAL = _get_or_create_counter(
        "ingest_new_contents_total",
        "Total new logical content rows created by ingest.",
        ("run_id", "phase"),
    )
    _PLANNER_ACTIONS_GENERATED_TOTAL = _get_or_create_counter(
        "planner_actions_generated_total",
        "Total actions generated by planner.",
        ("run_id", "phase"),
    )
    _APPLY_ACTIONS_EXECUTED_TOTAL = _get_or_create_counter(
        "apply_actions_executed_total",
        "Total actions executed by apply.",
        ("run_id", "phase"),
    )
    _PLANNER_STAGE_DURATION_SECONDS = _get_or_create_histogram(
        "planner_stage_duration_seconds",
        "Duration of planner stages in seconds",
        ("run_id", "stage"),
        buckets=(
            0.0001,
            0.0005,
            0.001,
            0.0025,
            0.005,
            0.01,
            0.025,
            0.05,
            0.1,
            0.25,
            0.5,
            1.0,
            2.5,
            5.0,
            10.0,
        ),
    )
    _CANONICAL_READ_CACHE_HITS_TOTAL = _get_or_create_counter(
        "canonical_read_cache_hits_total",
        "Total canonical metadata TTL cache hits by read source.",
        ("run_id", "source"),
    )
    _CANONICAL_READ_CACHE_MISSES_TOTAL = _get_or_create_counter(
        "canonical_read_cache_misses_total",
        "Total canonical metadata TTL cache misses by read source.",
        ("run_id", "source"),
    )
    _CANONICAL_READ_CACHE_HIT_RATIO_PERCENT = _get_or_create_gauge(
        "canonical_read_cache_hit_ratio_percent",
        "Canonical metadata TTL cache hit ratio expressed as percentage.",
        ("run_id", "source"),
    )
else:
    _INGEST_FILES_SCANNED_TOTAL = None
    _INGEST_NEW_CONTENTS_TOTAL = None
    _PLANNER_ACTIONS_GENERATED_TOTAL = None
    _APPLY_ACTIONS_EXECUTED_TOTAL = None
    _PLANNER_STAGE_DURATION_SECONDS = None
    _CANONICAL_READ_CACHE_HITS_TOTAL = None
    _CANONICAL_READ_CACHE_MISSES_TOTAL = None
    _CANONICAL_READ_CACHE_HIT_RATIO_PERCENT = None


def _normalize_run_id(run_id: str | None) -> str:
    normalized_run_id = str(run_id).strip() if run_id is not None else ""
    if not normalized_run_id:
        return "none"
    return normalized_run_id


def record_ingest_metrics(run_id: str, files_scanned: int, new_contents: int) -> None:
    """Record ingest counters with phase label `ingest`."""
    if _INGEST_FILES_SCANNED_TOTAL is None or _INGEST_NEW_CONTENTS_TOTAL is None:
        return
    try:
        _INGEST_FILES_SCANNED_TOTAL.labels(run_id=run_id, phase="ingest").inc(max(files_scanned, 0))
        _INGEST_NEW_CONTENTS_TOTAL.labels(run_id=run_id, phase="ingest").inc(max(new_contents, 0))
    except Exception:
        logger.exception("Failed to record ingest metrics")


def record_planner_metrics(run_id: str, actions_generated: int) -> None:
    """Record planner action counters with phase label `plan`."""
    if _PLANNER_ACTIONS_GENERATED_TOTAL is None:
        return
    try:
        _PLANNER_ACTIONS_GENERATED_TOTAL.labels(run_id=run_id, phase="plan").inc(max(actions_generated, 0))
    except Exception:
        logger.exception("Failed to record planner metrics")


def record_apply_metrics(run_id: str, actions_executed: int) -> None:
    """Record apply action counters with phase label `apply`."""
    if _APPLY_ACTIONS_EXECUTED_TOTAL is None:
        return
    try:
        _APPLY_ACTIONS_EXECUTED_TOTAL.labels(run_id=run_id, phase="apply").inc(max(actions_executed, 0))
    except Exception:
        logger.exception("Failed to record apply metrics")


def record_planner_stage_duration(run_id: str | None, stage: str, duration_s: float) -> None:
    """Record planner stage duration in seconds using run+stage labels.

    Labels:
    - run_id: durable planner run identifier
    - stage: planner stage name (load_candidates/metadata_lookup/action_generation/persist_actions)

    This helper is intentionally fail-open so planner execution is never impacted
    by metrics registry/runtime errors.
    """
    if _PLANNER_STAGE_DURATION_SECONDS is None:
        return
    try:
        normalized_run_id = _normalize_run_id(run_id)
        _PLANNER_STAGE_DURATION_SECONDS.labels(run_id=normalized_run_id, stage=stage).observe(max(duration_s, 0.0))
    except Exception:
        logger.exception("Failed to record planner stage duration")


def record_canonical_read_cache_metrics(
    run_id: str | None,
    source: str,
    cache_hits: int,
    cache_misses: int,
) -> None:
    """Record canonical metadata read cache counters and ratio gauge.

    The cache exposes cumulative in-memory totals. This helper converts them into
    monotonic counter increments by tracking per-label previous totals.
    """
    if (
        _CANONICAL_READ_CACHE_HITS_TOTAL is None
        or _CANONICAL_READ_CACHE_MISSES_TOTAL is None
        or _CANONICAL_READ_CACHE_HIT_RATIO_PERCENT is None
    ):
        return

    try:
        normalized_run_id = _normalize_run_id(run_id)
        normalized_source = source.strip().lower() or "unknown"
        clamped_hits = max(int(cache_hits), 0)
        clamped_misses = max(int(cache_misses), 0)
        label_key = (normalized_run_id, normalized_source)

        with _canonical_cache_metrics_lock:
            previous_hits, previous_misses = _canonical_cache_previous_totals.get(label_key, (0, 0))
            delta_hits = max(clamped_hits - previous_hits, 0)
            delta_misses = max(clamped_misses - previous_misses, 0)
            # Preserve monotonic reference totals to avoid overcounting when
            # concurrent calls submit out-of-order cumulative snapshots.
            _canonical_cache_previous_totals[label_key] = (
                max(previous_hits, clamped_hits),
                max(previous_misses, clamped_misses),
            )

        if delta_hits > 0:
            _CANONICAL_READ_CACHE_HITS_TOTAL.labels(run_id=normalized_run_id, source=normalized_source).inc(delta_hits)
        if delta_misses > 0:
            _CANONICAL_READ_CACHE_MISSES_TOTAL.labels(run_id=normalized_run_id, source=normalized_source).inc(
                delta_misses
            )

        total = clamped_hits + clamped_misses
        ratio_percent = 0.0 if total <= 0 else (100.0 * (clamped_hits / total))
        _CANONICAL_READ_CACHE_HIT_RATIO_PERCENT.labels(run_id=normalized_run_id, source=normalized_source).set(
            ratio_percent
        )
    except Exception:
        logger.exception("Failed to record canonical read cache metrics")


def record_canonical_read_cache_disabled(run_id: str | None, source: str) -> None:
    """Set canonical metadata read cache ratio gauge to 0 for disabled path."""
    if _CANONICAL_READ_CACHE_HIT_RATIO_PERCENT is None:
        return
    try:
        normalized_run_id = _normalize_run_id(run_id)
        normalized_source = source.strip().lower() or "unknown"
        _CANONICAL_READ_CACHE_HIT_RATIO_PERCENT.labels(run_id=normalized_run_id, source=normalized_source).set(0.0)
    except Exception:
        logger.exception("Failed to record canonical read cache disabled metric")


def mount_metrics_endpoint(app: object, path: str = "/metrics") -> bool:
    """Mount Prometheus ASGI endpoint and return True when mounted.

    The `app` object is expected to expose a Starlette/FastAPI-compatible `mount`
    method. Any failure is logged and converted to a False return.
    """
    if not _is_histogram_supported() or make_asgi_app is None:
        return False
    try:
        mount = getattr(app, "mount")
        mount(path, make_asgi_app())
        return True
    except Exception:
        logger.exception("Failed to mount Prometheus endpoint", extra={"phase": "observability"})
        return False


def start_metrics_http_server_if_enabled() -> bool:
    """Start standalone Prometheus HTTP server when explicitly enabled.

    Controlled by:
    - MEDIA_MANAGER_METRICS_ENABLED: `1/true/yes/on` enables startup.
    - MEDIA_MANAGER_METRICS_PORT: optional integer port (default: 9000).
    """
    global _server_started
    if not _is_server_supported():
        return False

    enabled_raw = os.getenv("MEDIA_MANAGER_METRICS_ENABLED", "0").strip().lower()
    if enabled_raw not in {"1", "true", "yes", "on"}:
        return False

    raw_port = os.getenv("MEDIA_MANAGER_METRICS_PORT", "9000").strip()
    try:
        port = int(raw_port)
    except ValueError:
        logger.warning(
            "Invalid MEDIA_MANAGER_METRICS_PORT value; skipping metrics server startup",
            extra={"phase": "observability", "action": "METRICS_SERVER", "codes_extracted": raw_port},
        )
        return False

    with _server_lock:
        if _server_started:
            return True
        try:
            start_http_server(port)
            _server_started = True
            logger.info(
                "Prometheus metrics HTTP server started",
                extra={"phase": "observability", "action": "METRICS_SERVER", "files_count": port},
            )
            return True
        except Exception:
            logger.exception("Failed to start Prometheus metrics HTTP server", extra={"phase": "observability"})
            return False


def generate_metrics_text() -> bytes:
    """Return raw Prometheus exposition payload bytes for tests/debugging."""
    if generate_latest is None:
        return b""
    try:
        return generate_latest()
    except Exception:
        logger.exception("Failed to generate Prometheus metrics payload")
        return b""


def read_counter_value(metric_name: str, labels: Mapping[str, str]) -> float:
    """Read a counter sample value by metric name/labels from current registry."""
    metric_line_prefix = f"{metric_name}{{"
    payload = generate_metrics_text().decode("utf-8", errors="ignore")
    for line in payload.splitlines():
        if not line.startswith(metric_line_prefix):
            continue
        if all(f'{key}="{value}"' in line for key, value in labels.items()):
            value_raw = line.rsplit(" ", maxsplit=1)[-1]
            try:
                return float(value_raw)
            except ValueError:
                return 0.0
    return 0.0
