"""Prometheus observability helpers for opt-in runtime metrics.

This module is intentionally fail-open:
- If prometheus_client is unavailable, all helpers become no-ops.
- Metrics setup errors never block planner/apply/CLI execution paths.
"""

from __future__ import annotations

import os
import threading
from collections.abc import Mapping

from media_manager.app.core.logging_config import get_logger

logger = get_logger(__name__)

try:
    from prometheus_client import Counter, REGISTRY, generate_latest, make_asgi_app, start_http_server
except Exception:  # pragma: no cover - fallback path when dependency is unavailable.
    Counter = None  # type: ignore[assignment]
    REGISTRY = None  # type: ignore[assignment]
    generate_latest = None  # type: ignore[assignment]
    make_asgi_app = None  # type: ignore[assignment]
    start_http_server = None  # type: ignore[assignment]

_server_lock = threading.Lock()
_server_started = False


def _can_mount_metrics() -> bool:
    return Counter is not None and make_asgi_app is not None


def _can_start_http_server() -> bool:
    return Counter is not None and start_http_server is not None


def _get_or_create_counter(name: str, documentation: str, labelnames: tuple[str, ...]):
    """Return a registered Counter, reusing an existing collector when present.

    This keeps module import robust under reload/hot-reload scenarios where the
    default registry already contains the same metric names.
    """
    if Counter is None:
        return None

    try:
        existing = None
        if REGISTRY is not None:
            names_to_collectors = getattr(REGISTRY, "_names_to_collectors", {})
            existing = names_to_collectors.get(name)
        if existing is not None:
            return existing
        return Counter(name, documentation, labelnames)
    except Exception:
        logger.exception("Failed to initialize counter", extra={"phase": "observability", "action": "METRICS_INIT"})
        return None


if Counter is not None:
    _INGEST_FILES_SCANNED_TOTAL = _get_or_create_counter(
        "ingest_files_scanned_total",
        "Total files scanned across ingest runs.",
        ("run_id", "phase"),
    )
    _INGEST_NEW_CONTENTS_TOTAL = _get_or_create_counter(
        "ingest_new_contents_total",
        "Total new logical content rows created by ingest.",
        ("run_id", "phase"),
    )
    _PLANNER_ACTIONS_GENERATED_TOTAL = _get_or_create_counter(
        "planner_actions_generated_total",
        "Total actions generated by planner.",
        ("run_id", "phase"),
    )
    _APPLY_ACTIONS_EXECUTED_TOTAL = _get_or_create_counter(
        "apply_actions_executed_total",
        "Total actions executed by apply.",
        ("run_id", "phase"),
    )
else:
    _INGEST_FILES_SCANNED_TOTAL = None
    _INGEST_NEW_CONTENTS_TOTAL = None
    _PLANNER_ACTIONS_GENERATED_TOTAL = None
    _APPLY_ACTIONS_EXECUTED_TOTAL = None


def record_ingest_metrics(run_id: str, files_scanned: int, new_contents: int) -> None:
    """Record ingest counters with phase label `ingest`."""
    if _INGEST_FILES_SCANNED_TOTAL is None or _INGEST_NEW_CONTENTS_TOTAL is None:
        return
    try:
        _INGEST_FILES_SCANNED_TOTAL.labels(run_id=run_id, phase="ingest").inc(max(files_scanned, 0))
        _INGEST_NEW_CONTENTS_TOTAL.labels(run_id=run_id, phase="ingest").inc(max(new_contents, 0))
    except Exception:
        logger.exception("Failed to record ingest metrics")


def record_planner_metrics(run_id: str, actions_generated: int) -> None:
    """Record planner action counters with phase label `plan`."""
    if _PLANNER_ACTIONS_GENERATED_TOTAL is None:
        return
    try:
        _PLANNER_ACTIONS_GENERATED_TOTAL.labels(run_id=run_id, phase="plan").inc(max(actions_generated, 0))
    except Exception:
        logger.exception("Failed to record planner metrics")


def record_apply_metrics(run_id: str, actions_executed: int) -> None:
    """Record apply action counters with phase label `apply`."""
    if _APPLY_ACTIONS_EXECUTED_TOTAL is None:
        return
    try:
        _APPLY_ACTIONS_EXECUTED_TOTAL.labels(run_id=run_id, phase="apply").inc(max(actions_executed, 0))
    except Exception:
        logger.exception("Failed to record apply metrics")


def mount_metrics_endpoint(app: object, path: str = "/metrics") -> bool:
    """Mount Prometheus ASGI endpoint and return True when mounted.

    The `app` object is expected to expose a Starlette/FastAPI-compatible `mount`
    method. Any failure is logged and converted to a False return.
    """
    if not _can_mount_metrics():
        return False
    try:
        mount = getattr(app, "mount")
        mount(path, make_asgi_app())
        return True
    except Exception:
        logger.exception("Failed to mount Prometheus endpoint", extra={"phase": "observability"})
        return False


def start_metrics_http_server_if_enabled() -> bool:
    """Start standalone Prometheus HTTP server when explicitly enabled.

    Controlled by:
    - MEDIA_MANAGER_METRICS_ENABLED: `1/true/yes/on` enables startup.
    - MEDIA_MANAGER_METRICS_PORT: optional integer port (default: 9000).
    """
    global _server_started
    if not _can_start_http_server():
        return False

    enabled_raw = os.getenv("MEDIA_MANAGER_METRICS_ENABLED", "0").strip().lower()
    if enabled_raw not in {"1", "true", "yes", "on"}:
        return False

    raw_port = os.getenv("MEDIA_MANAGER_METRICS_PORT", "9000").strip()
    try:
        port = int(raw_port)
    except ValueError:
        logger.warning(
            "Invalid MEDIA_MANAGER_METRICS_PORT value; skipping metrics server startup",
            extra={"phase": "observability", "action": "METRICS_SERVER", "codes_extracted": raw_port},
        )
        return False

    with _server_lock:
        if _server_started:
            return True
        try:
            start_http_server(port)
            _server_started = True
            logger.info(
                "Prometheus metrics HTTP server started",
                extra={"phase": "observability", "action": "METRICS_SERVER", "files_count": port},
            )
            return True
        except Exception:
            logger.exception("Failed to start Prometheus metrics HTTP server", extra={"phase": "observability"})
            return False


def generate_metrics_text() -> bytes:
    """Return raw Prometheus exposition payload bytes for tests/debugging."""
    if generate_latest is None:
        return b""
    try:
        return generate_latest()
    except Exception:
        logger.exception("Failed to generate Prometheus metrics payload")
        return b""


def read_counter_value(metric_name: str, labels: Mapping[str, str]) -> float:
    """Read a counter sample value by metric name/labels from current registry."""
    metric_line_prefix = f"{metric_name}{{"
    payload = generate_metrics_text().decode("utf-8", errors="ignore")
    for line in payload.splitlines():
        if not line.startswith(metric_line_prefix):
            continue
        if all(f'{key}="{value}"' in line for key, value in labels.items()):
            value_raw = line.rsplit(" ", maxsplit=1)[-1]
            try:
                return float(value_raw)
            except ValueError:
                return 0.0
    return 0.0
