-- PostgreSQL-compatible legacy schema bootstrap.
-- This script is intentionally idempotent and safe to run multiple times.

CREATE TABLE IF NOT EXISTS scans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    root_path TEXT NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at TIMESTAMPTZ,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id BIGINT NOT NULL REFERENCES scans(id),
    path TEXT NOT NULL,
    filename TEXT NOT NULL,
    extension TEXT,
    size_bytes BIGINT NOT NULL,
    mtime DOUBLE PRECISION,
    ctime DOUBLE PRECISION,
    hash_partial TEXT,
    hash_full TEXT,
    hash_algo TEXT,
    media_type TEXT CHECK (media_type IN ('image', 'video', 'audio', 'other')),
    duration DOUBLE PRECISION,
    width INTEGER,
    height INTEGER,
    codec TEXT,
    bitrate INTEGER,
    exif_datetime TEXT,
    is_hashed INTEGER NOT NULL DEFAULT 0,
    is_metadata_extracted INTEGER NOT NULL DEFAULT 0,
    camera_model TEXT,
    orientation TEXT
);

CREATE TABLE IF NOT EXISTS duplicate_candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id_1 BIGINT NOT NULL REFERENCES files(id),
    file_id_2 BIGINT NOT NULL REFERENCES files(id),
    match_type TEXT NOT NULL,
    confidence_score INTEGER NOT NULL CHECK (confidence_score BETWEEN 0 AND 100),
    reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    duplicate_group_id BIGINT,
    UNIQUE (file_id_1, file_id_2, match_type)
);

CREATE TABLE IF NOT EXISTS file_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id BIGINT NOT NULL REFERENCES files(id),
    action TEXT NOT NULL CHECK (action IN ('keep', 'move', 'delete', 'ignore', 'organize', 'rename')),
    target_path TEXT,
    decided_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    notes TEXT
);

CREATE TABLE IF NOT EXISTS deletion_audit_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    notes TEXT
);

CREATE TABLE IF NOT EXISTS deletion_audit_candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_run_id BIGINT NOT NULL REFERENCES deletion_audit_runs(id),
    reconstructed_name TEXT,
    observed_path TEXT NOT NULL,
    audit_notes TEXT,
    raw_actions_snapshot TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS deletion_audit_candidate_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_candidate_id BIGINT NOT NULL REFERENCES deletion_audit_candidates(id),
    related_file_id BIGINT NOT NULL REFERENCES files(id)
);

CREATE TABLE IF NOT EXISTS _tmp_deletion_audit_import (
    to_be_deleted_path TEXT,
    reconstructed_filename TEXT,
    found_in_db TEXT,
    file_id TEXT,
    actions TEXT,
    notes TEXT
);

CREATE INDEX IF NOT EXISTS idx_files_scan ON files(scan_id);
CREATE INDEX IF NOT EXISTS idx_files_size ON files(size_bytes);
CREATE INDEX IF NOT EXISTS idx_files_hash_full ON files(hash_full);
CREATE INDEX IF NOT EXISTS idx_files_hash_partial ON files(hash_partial);
CREATE INDEX IF NOT EXISTS idx_files_media_type ON files(media_type);
CREATE INDEX IF NOT EXISTS idx_files_size_media ON files(size_bytes, media_type);
CREATE INDEX IF NOT EXISTS idx_files_metadata ON files(duration, width, height, codec);

CREATE OR REPLACE VIEW files_needing_hash AS
SELECT f.*
FROM files f
JOIN (
    SELECT size_bytes
    FROM files
    GROUP BY size_bytes
    HAVING COUNT(*) > 1
) s ON f.size_bytes = s.size_bytes
WHERE f.hash_full IS NULL;

CREATE OR REPLACE VIEW exact_duplicates AS
SELECT hash_full, COUNT(*) AS cnt
FROM files
WHERE hash_full IS NOT NULL
GROUP BY hash_full
HAVING COUNT(*) > 1;
