-- PostgreSQL migration: widen file_actions.action domain to include organize/rename.

BEGIN;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = current_schema()
          AND table_name = 'file_actions'
    )
    AND NOT EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = current_schema()
          AND table_name = '_file_actions_old'
    ) THEN
        ALTER TABLE file_actions RENAME TO _file_actions_old;
    END IF;
END$$;

CREATE TABLE IF NOT EXISTS file_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id BIGINT NOT NULL REFERENCES files(id),
    action TEXT NOT NULL CHECK (action IN ('keep', 'move', 'delete', 'ignore', 'organize', 'rename')),
    target_path TEXT,
    decided_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    notes TEXT
);

INSERT INTO file_actions (id, file_id, action, target_path, decided_at, notes)
SELECT o.id, o.file_id, o.action, o.target_path, o.decided_at, o.notes
FROM _file_actions_old o
ON CONFLICT (id) DO NOTHING;

COMMIT;

SELECT COUNT(*) AS file_actions_count FROM file_actions;
